### ISSUE TITLE
Add submission time column to all published Activity Form Tables

### ISSUE THREAD

**Issue by karrla** [toladata/TolaTables#481]
### Story
Similiar to #477 and #480
When a user creates a form in Activity and publishes it, they would like the table created in Track to have a submission time (date/time would also be acceptable) stamp for each entry posted.

### Acceptance Criteria

GIVEN a user has a published form in Activity

WHEN they enter data into the form

THEN each submission will have a time stamp ( (date/time would also be acceptable) associated with it in the Track table.

**Comment by jefmoura** [comment]
As I talked to @joy-humanitec this ticket can be combined with the https://github.com/toladata/TolaTables/issues/480 and add only one column with the timestamp because timestamp is a combination of date and time. So, we'll add only a column like `| date + time |` instead of having two columns like `| date | time |` or `| date | date + time |`
